import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GeistMono } from 'geist/font/mono';
import clsx from 'clsx';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, GeistMono.className, 'bg-[#050505] text-[#E5E7EB]')}>
        <nav className="w-full p-4 font-mono text-sm border-b border-white/10 backdrop-blur-sm">
          NEXUS ALGO // THE VAULT
        </nav>
        {children}
      </body>
    </html>
  );
}